"""Agregar tipo_arqueo y tipo_venta

Revision ID: 03acf7581d1b
Revises: f82fe0f8b6f3
Create Date: 2026-07-21 09:33:53.504308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03acf7581d1b'
down_revision = 'f82fe0f8b6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arqueo_caja', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_arqueo', sa.String(length=50), server_default='general', nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_imei_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_products_imei'))
        batch_op.create_index(batch_op.f('ix_products_imei'), ['imei'], unique=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_venta', sa.String(length=50), server_default='general', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('tipo_venta')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_imei'))
        batch_op.create_index(batch_op.f('ix_products_imei'), ['imei'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('products_imei_key'), ['imei'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('arqueo_caja', schema=None) as batch_op:
        batch_op.drop_column('tipo_arqueo')

    # ### end Alembic commands ###
